import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PostModal from '../components/postModal'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bleep</title>
        <meta charSet="utf-8" />
        {/* <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PostModal/>   
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
